"""Contract tests for historical bounded reports.

After the Phase 10 scan/query slice, no report under
``docs/reports/generated/`` is regenerable from the maintained runtime.
Every report cites at least one command that depends on a module removed
during Phase 10, or on a module scheduled for removal.

The contract therefore checks only that:

1. every declared historical report remains present on disk;
2. reports in the structured subset retain their minimum structural
   markers (scope, observations, limits);
3. every markdown report under generated/ is declared;
4. no process document advertises a historical report as regenerable
   without a historical notice.
"""

from __future__ import annotations

from pathlib import Path

import pytest

# Reports generated by the historical PET runtime. Reproduction commands
# cited inside them no longer work. They are retained on disk as bounded
# historical evidence.
#
# ``structured`` = the report declares the full canonical structure
# (Scope, Observations, Limits/Interpretation).
HISTORICAL_REPORTS = {
    # Canonical bounded reports, with structural contract.
    "docs/reports/generated/metrics-2-10000.md": {
        "structured": True,
    },
    "docs/reports/generated/atlas-2-100000.md": {
        "structured": True,
    },
    "docs/reports/generated/atlas-2-1000000.md": {
        "structured": True,
    },
    "docs/reports/generated/families-benchmark-disjoint.md": {
        "structured": True,
    },
    "docs/reports/generated/signatures-catalog-2-1000000.md": {
        "structured": True,
    },
    # Research-facing reports, retained as evidence only.
    "docs/reports/generated/metica-range-sweep.md": {
        "structured": False,
    },
    "docs/reports/generated/metica-seven-family-300.md": {
        "structured": False,
    },
    "docs/reports/generated/metica-seven-family-500.md": {
        "structured": False,
    },
    "docs/reports/generated/metica-seven-family-800.md": {
        "structured": False,
    },
    "docs/reports/generated/metica-seven-family-900.md": {
        "structured": False,
    },
    "docs/reports/generated/metica-seven-family-1200.md": {
        "structured": False,
    },
    "docs/reports/generated/rewrite-1-30-overscan-90.md": {
        "structured": False,
    },
    "docs/reports/generated/rewrite-demo-1-10-overscan-40.md": {
        "structured": False,
    },
}

EXISTING_HISTORICAL_REPORTS = {
    path: spec
    for path, spec in HISTORICAL_REPORTS.items()
    if Path(path).exists()
}

STRUCTURED_REPORTS = {
    path: spec
    for path, spec in EXISTING_HISTORICAL_REPORTS.items()
    if spec["structured"]
}


def read_text(path: str) -> str:
    file_path = Path(path)
    assert file_path.exists(), f"Expected report file to exist: {path}"
    return file_path.read_text(encoding="utf-8")


def assert_common_report_markers(text: str, path: str) -> None:
    assert "## Scope" in text, f"{path}: missing '## Scope' section"
    assert "## Observations" in text, f"{path}: missing '## Observations' section"

    has_limits = (
        "## Interpretation and limits" in text or "## Limits" in text
    )
    assert has_limits, f"{path}: missing limits/interpretation section"


@pytest.mark.parametrize(
    "path,spec", EXISTING_HISTORICAL_REPORTS.items()
)
def test_historical_report_is_present(path: str, spec: dict) -> None:
    """Every declared historical report remains on disk."""

    text = read_text(path)
    assert text.strip(), f"{path}: report is empty"


@pytest.mark.parametrize(
    "path,spec", STRUCTURED_REPORTS.items()
)
def test_structured_historical_report_has_markers(
    path: str, spec: dict
) -> None:
    """Structured reports retain their canonical markers."""

    text = read_text(path)
    assert_common_report_markers(text, path)


def test_all_generated_reports_are_declared_historical() -> None:
    """Every markdown report under generated/ is in the declared set."""

    generated = Path("docs/reports/generated")
    if not generated.is_dir():
        pytest.skip("generated report directory missing")

    on_disk = {
        str(p) for p in generated.glob("*.md") if p.is_file()
    }
    declared = set(HISTORICAL_REPORTS.keys())

    undeclared = on_disk - declared
    assert not undeclared, (
        "generated reports not declared as historical: "
        + ", ".join(sorted(undeclared))
    )


def test_active_process_docs_do_not_advertise_historical_reports() -> None:
    """Process docs may not present historical reports as regenerable."""

    process_docs = [
        Path("docs/reports/process/canonical-workflow.md"),
        Path("docs/reports/process/contributor-operator.md"),
    ]

    for doc in process_docs:
        if not doc.exists():
            continue
        text = doc.read_text(encoding="utf-8")
        has_disclaimer = (
            "Phase 10 historical notice" in text
            or "historical" in text.lower()
        )
        for report in HISTORICAL_REPORTS:
            name = Path(report).name
            if name in text and not has_disclaimer:
                raise AssertionError(
                    f"{doc}: references {name} without a historical "
                    "disclaimer"
                )
