"""Public API for the PETRA shape-first runtime."""

from .addresses import (
    Address,
    AddressError,
    ResolvedAnchor,
    ResolvedSlot,
    ResolvedTerm,
    parse_address,
    render_address,
    resolve_address,
)
from .model import (
    CanonicalData,
    Container,
    Leaf,
    PetraShape,
    Root,
    Term,
    normalize_shape,
    to_canonical_data,
    validate_shape,
)
from .results import (
    AddressEffects,
    DefaultTarget,
    ExplicitTarget,
    FailedResult,
    InvocationTarget,
    Operator,
    OperatorResult,
    SuccessfulResult,
)
from .operators import (
    apply_graft,
    apply_prune,
    apply_shed,
    apply_sprout,
)

__all__ = [
    "Address",
    "AddressEffects",
    "AddressError",
    "CanonicalData",
    "Container",
    "DefaultTarget",
    "ExplicitTarget",
    "FailedResult",
    "InvocationTarget",
    "Leaf",
    "Operator",
    "OperatorResult",
    "PetraShape",
    "ResolvedAnchor",
    "ResolvedSlot",
    "ResolvedTerm",
    "Root",
    "SuccessfulResult",
    "Term",
    "normalize_shape",
    "parse_address",
    "render_address",
    "resolve_address",
    "to_canonical_data",
    "apply_graft",
    "apply_prune",
    "apply_shed",
    "apply_sprout",
    "validate_shape",
]
